Scripts: Check num of args (HardLinkDir)

diff --git a/Scripts/HardLinkDir b/Scripts/HardLinkDir
--- a/Scripts/HardLinkDir
+++ b/Scripts/HardLinkDir
@@ -10,6 +10,11 @@ if [ -e "$2" ] && [ ! -d "$2" ]; then
     exit 1
 fi
 
+if [ "$#" -ne 2 ]; then
+    echo "Invalid number of arguments."
+    exit 1
+fi
+
 echo "Linking contents of: $1 to: $2"
 read -p 'Continue? (y/n) ' confirmation
 
